### ISSUE TITLE
Add Missing Tests

### ISSUE THREAD

**Issue by AntonioJuliano** [dydxprotocol/protocol#147]
Tests we should add:

**Base Protocol**

`InterestImpl`:
- [x] [less than 128 bits](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/InterestImpl.sol#L95) (fixed in #272)

`OpenPositionShared`:
- [x] [Fee Recipient is 0](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/OpenPositionShared.sol#L231) (fixed in #251)
- [x] [Valid Taker](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/OpenPositionShared.sol#L101) (fixed in #251)
- [x] [0 Position Owner](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/OpenPositionShared.sol#L101) (fixed in #251)
- [x] [0 Loan Offering Owner](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/OpenPositionShared.sol#L129) (fixed in #251)
- [x] [Interest Period Over Maximum Duration](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/OpenPositionShared.sol#L129) (fixed in #251)
- [x] [verifyLoanOffering returns false](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/OpenPositionShared.sol#L171) (fixed in #251)
- [x] [0 lender fee](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/OpenPositionShared.sol#L248) (fixed in #251)
- [x] [0 taker fee](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/OpenPositionShared.sol#L257) (fixed in #251)

`ClosePositionShared`:
- [x] [0 payoutRecipient](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/ClosePositionShared.sol#L141) (fixed in #255)
- [x] [closeOnBehalfOf returns a greater value](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/ClosePositionShared.sol#L234) (fixed in #255)
- [x] [liquidateOnBehalfOf returns a greater value](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/ClosePositionShared.sol#L247) (fixed in #255)

`IncreasePositionImpl`:
- [x] [position increased after maxDuration](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/IncreasePositionImpl.sol#L206) (fixed in #252)
- [x] [buy order gives too much `heldToken`](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/IncreasePositionImpl.sol#L238) (fixed in #254)
- [x] [buy order gives too much `heldToken` (depositing in owed token)](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/IncreasePositionImpl.sol#L249) (fixed in #254)
- [x] [lender refuses the increase](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/IncreasePositionImpl.sol#L306) (fixed in #254)

`ClosePositionImpl`:
- [x] [cannot payout in base token if no exchange wrapper](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/ClosePositionImpl.sol#L108)
- [x] [cannot close if too much `owedToken` owed to lender](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/ClosePositionImpl.sol#L190)

`LoanImpl`:
- [x] [canceling 0 on loan offering](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/LoanImpl.sol#L165)

`MarginCommon`:
- [x] [interestPeriod is 0 or 1](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/MarginCommon.sol#L128)

`PositionGetters`:
- [x] [`getTimeUntilInterestIncrease` when past `maxDuration`](https://coveralls.io/builds/16786215/source?filename=contracts/margin/impl/PositionGetters.sol#L130) (fixed in #244)

**lib**

`TokenInteract`:
- [x] [approve fails](https://coveralls.io/builds/16786215/source?filename=contracts/lib/TokenInteract.sol#L44)
- [x] [transfer fails](https://coveralls.io/builds/16786215/source?filename=contracts/lib/TokenInteract.sol#L62)
- [x] [`amount == 0`](https://coveralls.io/builds/16786215/source?filename=contracts/lib/TokenInteract.sol#L73)
- [x] [`from == to`](https://coveralls.io/builds/16786215/source?filename=contracts/lib/TokenInteract.sol#L73)

`Exponent`:
- [x] [`precomputePrecision` over max](https://coveralls.io/builds/16786215/source?filename=contracts/lib/Exponent.sol#L52)

`FractionMath`:
- [x] [`overflow on #add`](https://coveralls.io/builds/16786215/source?filename=contracts/lib/FractionMath.sol#L30) (fixed in #260)
- [x] [#sub](https://coveralls.io/builds/16786215/source?filename=contracts/lib/FractionMath.sol#L53) (fixed in #260)
- [x] [#mul](https://coveralls.io/builds/16786215/source?filename=contracts/lib/FractionMath.sol#L101) (fixed in #260)

`StaticAccessControlled`:
- [x] [does not grant access after grace period](https://coveralls.io/builds/16786215/source?filename=contracts/lib/StaticAccessControlled.sol#L43)

**External**

`ERC20Long`:
- [x] (fixed in #263)

`ERC20LongCreator`:
- [x] (fixed in #250)

`ERC20Position`:
- [x] (fixed in #250)

`ERC721MarginLoan`:
- [x] [`#marginLoanIncreased`](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/ERC721/ERC721MarginLoan.sol#L246) (fixed in #275)
- [x] [does not allow `#withdraw` for nonexistent tokens](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/ERC721/ERC721MarginLoan.sol#L330) (fixed in #275)

`ERC721MarginPosition`:
- [x] [`#burnTokenSafe`](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/ERC721/ERC721MarginPosition.sol#L168) (to be fixed in #276)
- [x] [`#marginPositionIncreased`](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/ERC721/ERC721MarginPosition.sol#L216) (fixed in #275)

`ZeroExExchangeWrapper`:
- [x] [0 fee recipient](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/exchangewrappers/ZeroExExchangeWrapper.sol#L245) (fixed in #273)
- [x] [fails if order is too small](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/exchangewrappers/ZeroExExchangeWrapper.sol#L206) (fixed in #273)
- [x] [fails if the order is already filled](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/exchangewrappers/ZeroExExchangeWrapper.sol#L227) (fixed in #273)

`DutchAuctionCloser`:
- [x] [constructor throws on invalid fraction](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/DutchAuctionCloser.sol#L69) (fixed in #266)
- [x] [constructor throws on 0 fraction](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/DutchAuctionCloser.sol#L70) (fixed in #266)
- [x] [disallows paying out in owed token](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/DutchAuctionCloser.sol#L104) (fixed in #266)
- [x] [auction from `maxTimestamp`](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/DutchAuctionCloser.sol#L177) (fixed in #266)

`SharedLoan`:
- [x] [only accepts ownership of 1 loan](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/SharedLoan.sol#L145) (fixed in #244)
- [x] [only accepts ownership of the specified loan](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/SharedLoan.sol#L146) (fixed in #244)
- [x] [disallows #withdrawMultiple when uninitialized](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/SharedLoan.sol#L292) (fixed in #244)
- [x] [disallows #withdraw when uninitialized](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/SharedLoan.sol#L317) (fixed in #244)
- [x] [automatically sets state to closed](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/SharedLoan.sol#L330) (fixed in #274)
- [x] [withdrawing 0 held tokens](https://coveralls.io/builds/16786215/source?filename=contracts/margin/external/SharedLoan.sol#L425) (fixed in #274)

_Updated 4/1/18 - 7d53e2b7c5b8b0464959a52d1e35cab51e716d3a_
